modLoader="javafml"
loaderVersion="[43,)"
license="${mod_license}"
issueTrackerURL="https://github.com/mutualzz/mutualzz/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Mutualzz"
displayURL="https://mutualzz.com"
description='''
In-game mic and speakers for Mutualzz voice channels. Requires the MutualzzBridge Paper plugin on the server.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
